#!/usr/bin/env bash
set -eu

progdir=$(cd "$(dirname "$0")" && pwd -P)
export progdir
source "$progdir/scripts/peering-config"

usage () {
    cat <<-EOF
usage: $0 openvpn|bgp|bgp6|prefix|proxy|app

openvpn     Control OpenVPN tunnels

bgp         Control IPv4 BGP router (BIRD)

bgp6        Control IPv6 BGP router (BIRD6)

prefix      Control prefix announcements

proxy       Control proxy for containers

app         Create and delete namespaces/bridges for applications

EOF
    exit 0
}

test $# -ge 1 || usage

case $1 in
openvpn)
    shift
    "$progdir/scripts/peering-openvpn" "$@"
    ;;
bgp)
    shift
    "$progdir/scripts/peering-bgp" "$@"
    ;;
bgp6)
    shift
    "$progdir/scripts/peering-bgp" v6 "$@"
    ;;
prefix)
    shift
    "$progdir/scripts/peering-prefix" "$@"
    ;;
proxy)
    shift
    "$progdir/scripts/peering-proxy" "$@"
    ;;
app)
    shift
    "$progdir/scripts/peering-app" "$@"
    ;;
*)
    usage
    ;;
esac
