#!/bin/bash
set -eu

program=$(basename $0)
progdir=$(cd $(dirname $0); pwd -P)
. $progdir/peering-config

usage () {
    cat <<-EOF
usage: $0 status|up mux|down mux

status      Show the status of configured OpenVPN tunnels.

up mux      Bring tunnel to mux up.

down mux    Bring tunnel to mux down.

EOF
    exit 0
}

mux_status_check() {
    local mux=$1
    local dev=${mux2dev[$mux]:-unset}
    test $dev != "unset" || die "error [mux $mux unknown]"
    local pidfn="$openvpn_logs/$dev.pid"
    if [ ! -s $pidfn ] ; then
        mstat="down"
        return
    fi
    if ! kill -0 $(cat $pidfn) &> /dev/null ; then
        die "error [$pidfn exists but cannot send signal]"
    fi
    local statfn="$openvpn_logs/$dev.status"
    if [ ! -s $statfn ] ; then
        mstat="down"
    else
        mstat=$(head -n 1 $statfn | cut -d " " -f 1,2)
    fi
}

test $# -ge 1 || usage

case $1 in
up)
    test $# -ge 2 || usage
    mux=$2
    mux_status_check $mux
    if [[ $mstat =~ ^up.*$ ]] ; then term "tunnel $mux already up" ; fi
    openvpn --cd $(pwd)/openvpn --config configs/$mux.conf
    ;;
down)
    test $# -ge 2 || usage
    mux=$2
    mux_status_check $mux
    if [[ $mstat =~ ^down$ ]] ; then term "tunnel $mux already down" ; fi
    dev=${mux2dev[$mux]}
    kill -SIGINT $(cat $openvpn_logs/$dev.pid)
    rm -f $openvpn_logs/$dev.pid
    rm -f $openvpn_logs/$dev.status
    ;;
status)
    for mux in ${!mux2dev[@]} ; do
        mux_status_check $mux
        echo "$mux ${mux2dev[$mux]} $mstat"
    done | sort
    ;;
*)
    usage
    ;;
esac
