#!/bin/bash
set -eu

program=$(basename $0)
progdir=$(cd $(dirname $0); pwd -P)
. $progdir/peering-config

usage () {
    cat <<-EOF
usage: $0 openvpn|bgp|prefix

openvpn     Control OpenVPN tunnels

bgp         Control BGP router (BIRD)

prefix      Control prefix announcements

EOF
    exit 0
}

test $# -ge 1 || usage

case $1 in
openvpn)
    shift
    ./peering-openvpn $@
    ;;
bgp)
    shift
    ./peering-bgp $@
    ;;
prefix)
    shift
    ./peering-prefix $@
    ;;
*)
    usage
    ;;
esac
