#!/bin/bash
set -eu

program=$(basename $0)
progdir=$(cd $(dirname $0); pwd -P)
. $progdir/peering-config

mux=all
poison=0
origin=0
prefix=invalid

do_announce () {
    local mux=$1
    filterfn="$bird_filters/export_${mux}_$prefixfn.conf"
    echo "if ( net = $prefix ) then {" > $filterfn
    if [ $poison -ne 0 ] ; then
    echo "    bgp_path.prepend(47065);" >> $filterfn
    echo "    bgp_path.prepend($poison);" >> $filterfn
    elif [ $origin -ne 0 ] ; then
    echo "    bgp_path.prepend($origin);" >> $filterfn
    fi
    echo "    accept;" >> $filterfn
    echo "}" >> $filterfn
    filterfn=$bird_routes/$prefixfn
    echo "route $prefix unreachable;" > $filterfn
}

usage () {
    cat <<-EOF
Usage: peering prefix announce|withdraw [-m mux] [-p poison] prefix

announce    Announce prefix from one or all muxes.
withdraw    Withdraw prefix from one or all muxes.

-m mux      Control which mux the prefix should be announced to
            or withdrawn from.  [default: $mux]
-p asn      Prepend announcement to include the given ASN in the
            AS-path and trigger BGP loop prevention (poisoning).
            Also known as BGP poisoning.  [default: do not poison]
-o asn      Prepend annoucnement to include the given ASN as the
            origin of the announcement.  [default: keep unchanged]

prefix      Choose the prefix to operate on.  Make sure the prefix
            has been allocated to you, or your announcement will be
            filtered by PEERING muxes.

EOF
    exit 0
}

test $# -ge 2 || usage

OPTIND=2
while getopts "m:p:" opt $* ; do
case $opt in
m)  mux=$OPTARG ;;
p)  poison=$OPTARG ;;
o)  origin=$OPTARG ;;
*)  usage
esac
done

if [ $mux != all -a ${mux2dev[$mux]:-unset} = unset ] ; then
    die "error [mux unknown: $mux]"
fi

if [[ $poison -ne 0 ]] ; then
    if [[ ! $poison =~ [0-9]+ ]] ; then
        die "error [poisoned AS should be a number]"
    elif [[ $poison -gt 65535 || $poison -lt 1 ]] ; then
        die "error [poisoned AS not a  16-bit number]"
    fi
fi

if [[ $origin -ne 0 ]] ; then
    if [[ ! $origin =~ [0-9]+ ]] ; then
        die "error [origin AS should be a number]"
    elif [[ $origin -gt 65535 || $origin -lt 1 ]] ; then
        die "error [origin AS not a  16-bit number]"
    fi
fi

if [[ $poison -ne 0 && $origin -ne 0 ]] ; then
    die "error [cannot -p and -o at the same time]"
fi

prefix=${!OPTIND:-unset}
pfxid=${pfx2id[$prefix]:-unset}
if [ $pfxid = unset ] ; then
    echo "list of PEERING prefixes:"
    cut -d " " -f 1 $bird_cfgs/pfx2id.txt
    die "error [invalid prefix: $prefix]"
fi
prefixfn=${prefix/\//-}

subcmd=$1
case $subcmd in
announce)
    if [ $mux = all ] ; then
        for cmux in ${!mux2dev[@]} ; do
            do_announce $cmux
        done
    else
        do_announce $mux
    fi
    echo "configure \"$bird_cfgs/bird.conf\"" | birdc -s $bird_sock
    ;;
withdraw)
    if [ $mux = all ] ; then
        for cmux in ${!mux2dev[@]} ; do
            rm -f $bird_cfgs/export_${cmux}_$prefixfn.conf
        done
    else
        rm -f $bird_cfgs/export_${mux}_$prefixfn.conf
    fi
    echo "configure \"$bird_cfgs/bird.conf\"" | birdc -s $bird_sock
    ;;
*)
    usage
    ;;
esac
