[project]
name = "large-scale"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dataclasses-json>=0.6.7",
    "jinja2>=3.1.6",
    "jsonschema>=4.25.1",
    "requests>=2.32.5",
]
