#!/bin/bash
set -eu

# program=$(basename $0)
# progdir=$(cd $(dirname $0); pwd -P)
# . $progdir/peering-config

mux=all
poison=0
origin=0
prefix=invalid
communities=()

do_announce () {
    local mux=$1
    filterfn="$bird_filters/export_${mux}_$prefixfn.conf"
    echo "if ( net = $prefix ) then {" > $filterfn
    if [ $poison -ne 0 ] ; then
    echo "    bgp_path.prepend(47065);" >> $filterfn
    echo "    bgp_path.prepend($poison);" >> $filterfn
    elif [ $origin -ne 0 ] ; then
    echo "    bgp_path.prepend($origin);" >> $filterfn
    fi
    if [[ ${communities[@]:-undef} != "undef" ]] ; then
        for comm in "${communities[@]}" ; do
            echo "    bgp_community.add((47065,$comm));" >> $filterfn;
        done
    fi
    echo "    accept;" >> $filterfn
    echo "}" >> $filterfn
    filterfn=$bird_routes/$prefixfn
    echo "route $prefix unreachable;" > $filterfn
}

usage () {
    cat <<-EOF
Usage: peering prefix announce|withdraw [-m mux] [-p poison|-o origin]
                                        [-c id1] ... [-c idN] prefix

Options can be specified in any order, but announce|withdraw must
be the first argument and prefix must be the last.

announce    Announce prefix from one or all muxes.
withdraw    Withdraw prefix from one or all muxes.

-m mux      Control which mux the prefix should be announced to
            or withdrawn from.  [default: $mux]
-p asn      Prepend announcement to include the given ASN in the
            AS-path and trigger BGP loop prevention (poisoning).
            Also known as BGP poisoning.  [default: do not poison]
-o asn      Prepend annoucnement to include the given ASN as the
            origin of the announcement.  [default: keep unchanged]
            Cannot be combined with -p.
-c id       Attach community (47065,id) to the announcement.  This
            will let the announcement through peer with the given
            id.  May be added multiple times to announce from
            multiple peers.  [default: announce to all peers]
            (see https://peering.usc.edu/peers for the list of peers)

prefix      Choose the prefix to operate on.  Make sure the prefix
            has been allocated to you, or your announcement will be
            filtered by PEERING muxes.

EOF
    exit 0
}

test $# -ge 2 || usage
test $EUID -eq 0 || die "The BIRD BGP daemon requires root access."

OPTIND=2
while getopts "m:p:o:c:" opt $* ; do
case $opt in
m)  mux=$OPTARG ;;
p)  poison=$OPTARG ;;
o)  origin=$OPTARG ;;
c)
    if [[ $OPTARG -gt 65535 || $OPTARG -lt 1 ]] ; then
        die "error [-c id accepts only 16-bit numbers]"
    fi
    communities+=($OPTARG)
    ;;
*)  usage
esac
done

declare -A mux2dev
while read fmux fdev ; do
    mux2dev[$fmux]=$fdev
done < $mux2dev_db

if [ $mux != all -a ${mux2dev[$mux]:-unset} = unset ] ; then
    die "error [mux unknown: $mux]"
fi

if [[ $poison -ne 0 ]] ; then
    if [[ ! $poison =~ [0-9]+ ]] ; then
        die "error [poisoned AS should be a number]"
    elif [[ $poison -gt 65535 || $poison -lt 1 ]] ; then
        die "error [poisoned AS not a  16-bit number]"
    fi
fi

if [[ $origin -ne 0 ]] ; then
    if [[ ! $origin =~ [0-9]+ ]] ; then
        die "error [origin AS should be a number]"
    elif [[ $origin -gt 65535 || $origin -lt 1 ]] ; then
        die "error [origin AS not a  16-bit number]"
    fi
fi

if [[ $poison -ne 0 && $origin -ne 0 ]] ; then
    die "error [cannot -p and -o at the same time]"
fi

declare -A pfx2id
while read pfx ; do
    pfx2id[$pfx]=enabled
done < $prefix_db

prefix=${!OPTIND:-unset}
pfxid=${pfx2id[$prefix]:-unset}
if [ $pfxid = unset ] ; then
    echo "list of configured prefixes:"
    cut -d " " -f 1 $progdir/prefixes.txt
    die "error [invalid prefix: $prefix]"
fi
prefixfn=${prefix/\//-}
pfxdot1=$(echo $prefix | sed "s|\.0/|.1/|")

subcmd=$1
case $subcmd in
announce)
    if [ $mux = all ] ; then
        for cmux in ${!mux2dev[@]} ; do
            do_announce $cmux
        done
    else
        do_announce $mux
    fi
    echo "configure \"$bird_cfgs/bird.conf\"" | birdc -s $bird_sock
    if ! ip addr add $pfxdot1 dev lo ; then
        echo "error adding addr $pfxdot1 to loopback interface"
    fi
    ;;
withdraw)
    if [ $mux = all ] ; then
        for cmux in ${!mux2dev[@]} ; do
            rm -f $bird_filters/export_${cmux}_$prefixfn.conf
        done
    else
        rm -f $bird_filters/export_${mux}_$prefixfn.conf
    fi
    echo "configure \"$bird_cfgs/bird.conf\"" | birdc -s $bird_sock
    if ! ip addr del $pfxdot1 dev lo ; then
        echo "error removing addr $pfxdot1 from loopback interface"
    fi
    ;;
*)
    usage
    ;;
esac
