#!/usr/bin/env bash
set -eu

# program=$(basename $0)
# progdir=$(cd $(dirname $0); pwd -P)
# . $progdir/peering-config

mux=all
poison_list=()
prepend=0
origin=0
prefix=invalid
config_dataplane=1
communities=()
large_communities=()
lxc_dataplane=0

check_valid_asn () {  # {{{
    local asn=$1
    if [[ $asn -ne 0 ]] ; then
        if [[ ! $asn =~ [0-9]+ ]] ; then
            die "error [AS ($asn) should be a number]"
        elif [[ $asn -lt 1 ]] ; then
            die "error [AS ($asn) should be a positive number]"
        fi
    fi
}  # }}}

client_nexthop () {
    local mux=$1
    local dev=${mux2dev[$mux]}
    local devid=${dev##tap}
    local mux_offset="$(( devid << 3 ))"
    local ctxid=$(cat "$ctxid_db")
    local cont_offset="$(( ctxid*4 + 2 ))"
    echo "100.125.$mux_offset.$cont_offset"
}

do_announce () {  #{{{
    local mux=$1
    local filterfn="$bird_filters/export_${mux}_$prefixfn.conf"
    echo "if ( net = $prefix ) then {" > "$filterfn"
    if [[ $origin -eq 0 ]] ; then origin=47065 ; fi
    if [[ $prepend -eq 0 ]] ; then
        if [[ ${poison_list[*]:-undef} != undef ]] \
                || [[ $origin -ne 47065 ]] ; then
            prepend=1
        fi
    fi
    if [[ $prepend -ne 0 ]] ; then
        for _ in $(seq 1 $prepend) ; do
            echo "    bgp_path.prepend($origin);" >> "$filterfn"
        done
    fi
    if [[ ${poison_list[*]:-undef} != undef ]] ; then
        for poison in "${poison_list[@]}" ; do
            echo "    bgp_path.prepend($poison);" >> "$filterfn"
        done
        if [[ $origin -ne 47065 ]] \
                && [[ ${poison_list[-1]} -ne $origin ]] ; then
            echo "    bgp_path.prepend($origin);" >> "$filterfn"
        fi
    fi
    if [[ ${communities[*]:-undef} != undef ]] ; then
        for comm in "${communities[@]}" ; do
            echo "    bgp_community.add(($comm));" >> "$filterfn"
        done
    fi
    if [[ ${large_communities[*]:-undef} != undef ]] ; then
        for comm in "${large_communities[@]}" ; do
            echo "    bgp_large_community.add(($comm));" >> "$filterfn"
        done
    fi
    if [[ $lxc_dataplane -eq 1 ]] ; then
        echo "    bgp_next_hop=$(client_nexthop "$mux");" >> "$filterfn"
    fi
    echo "    accept;" >> "$filterfn"
    echo "}" >> "$filterfn"
    filterfn=$bird_routes/$prefixfn
    echo "route $prefix unreachable;" > "$filterfn"
}  #}}}

usage () {  # {{{
    cat <<-EOF
Usage: peering prefix announce|withdraw [-m mux [-M]]
                                        [-P prepend] [-o origin]
                                        [-p poison] ... [-p poison]
                                        [-c ASN,COMM] ... [-c ASN,COMM]
                                        [-l ASN,X,Y] ... [-l ASN,X,Y]
                                        [-R] [-M]
                                        prefix

Options can be specified in any order, but announce|withdraw must
be the first argument and prefix must be the last.

announce    Announce prefix to one or all muxes.
withdraw    Withdraw prefix to one or all muxes.

-m mux      Control to which mux the prefix should be announced
            or withdrawn.  [default: $mux]

-p asn      Prepend announcement to include the given ASN in the AS-path
            and trigger BGP loop prevention. Also known as BGP poisoning.
            Can be used multiple times to poison multiple ASNs. Sets -P
            to 1 if not specified, and enforces the origin ASN (-o) is
            prepended after the poisons. [default: do not poison]

-P N        Prepend origin (given with -o) N times.  [default: 0]

-o asn      Prepend announcement to include the given ASN as the
            origin of the announcement. Sets -P to 1 if not specified.
            [default: unchanged (47065)]

-c ASN,COMM Attach community ASN,COMM to the announcement.  Can be used
            multiple times to attach multiple communities.  Only
            PEERING-operated ASes are allowed for ASN.  Both ASN and
            COMM are limited to 16-bit numbers.

            Communities in the range 47065,0--2000 have special meaning:

            - Community 47065,0 indicates that an announcement should be
              announced to remote peers through AL2S.
            - Communities 47065,X (1 <= X <= 1000) indicate that the
              announcement should be exported to peer X.
            - Communities 47065,1000+X (1 <= X <= 1000) indicate that
              the announcement should not be exported to the peer X.

            Announcements through each peer only see their filtering
            community.  The default behavior is to announce to all
            peers.  See https://peering.ee.columbia.edu/peers for the
            list of peers and their IDs.

            Special communities in the range 65535,65281--65284 defined
            in RFCs 1997 and 3765 are filtered and have no effect.

            A maximum of 20 communities (not including the special
            communities above) is allowed in any announcement.  If the
            number of communities exceeds 20, all communities will be
            filtered.

-l ASN,F,V  Attach large community ASN,F,V to the announcement.  Can be
            used multiple times to attach multiple large communities.
            (Large communities are filtered by default and allowed upon
            request.)

-R          Do not configure the data plane.  We setup a working data
            plane by adding the .1 address of announced prefixes to the
            loopback interface and setting outgoing packets to use
            table 20000, which is populated by BIRD.  This flag skips
            configuration of the data plane, and is particularly useful
            if using the app submodule to avoid conflicting routing
            rules.

-M          Change the announcement's next-hop, configuring a mux to
            redirect packets into the user's container.  Must be used
            with -m and a mux running a container.

prefix      Choose the prefix to operate on.  Make sure the prefix
            has been allocated to you, or your announcement will be
            filtered by PEERING muxes.

EOF
    exit 0
}  # }}}


test $# -ge 2 || usage
test $EUID -eq 0 || die "The BIRD BGP daemon requires root access."

OPTIND=2  # {{{
while getopts "m:p:P:o:c:C:l:RM" opt "$@" ; do
case $opt in
m)  mux=$OPTARG ;;
p)  poison_list+=("$OPTARG") ;;
P)  prepend=$OPTARG ;;
o)  origin=$OPTARG ;;
c|C)
    if ! [[ $OPTARG =~ [0-9]+,[0-9]+ ]] ; then
        die "error [-c requires a string that matches '[0-9]+,[0-9]+']"
    fi
    ctoken=${OPTARG%,*}
    if [[ $ctoken -gt 65535 || $ctoken -lt 0 ]] ; then
        die "error [-c ASN:COMM accepts only 16-bit numbers]"
    fi
    ctoken=${OPTARG#*,}
    if [[ $ctoken -gt 65535 || $ctoken -lt 0 ]] ; then
        die "error [-c ASN:COMM accepts only 16-bit numbers]"
    fi
    communities+=("$OPTARG")
    ;;
l)
    if ! [[ $OPTARG =~ [0-9]{1,9},[0-9]{1,9},[0-9]{1,9} ]] ; then
        die "error [-l requires a string that matches '[0-9]{1,9},[0-9]{1,9},[0-9]{1,9}']"
    fi
    large_communities+=("$OPTARG")
    ;;
R)
    config_dataplane=0
    ;;
M)
    if [[ ! -e "$ctxid_db" ]] ; then
        die "error [create a $ctxid_db file with your container's ID]"
    fi
    lxc_dataplane=1
    ;;
*)  usage
esac
done  # }}}

load_mux2dev
load_pfx2id

if [ "$mux" != all ] && [ "${mux2dev[$mux]:-unknown}" = unknown ] ; then
    die "error [mux unknown: $mux]"
fi

if [[ $lxc_dataplane -eq 1 && $mux == all ]] ; then
    die "error [-M can only be used with -m]"
fi

if [[ ${poison_list[*]:-undef} != undef ]] ; then
    for poison in "${poison_list[@]}" ; do
        check_valid_asn "$poison"
    done
fi
check_valid_asn "$origin"

if [[ $prepend -lt 0 || $prepend -gt 4 ]] ; then
    die "error [can prepend only 1, 2, 3, or 4 times]"
fi

prefix=${!OPTIND:-unknown}
pfxid=${pfx2id[$prefix]:-unknown}
if [[ $pfxid == unknown ]] ; then
    echo "list of configured prefixes:"
    cat "$prefix_db" "$prefix6_db"
    die "error [invalid prefix: $prefix]"
fi

prefixfn=${prefix/\//-}
pfxdot1=${prefix/\.0\//.1\/}
minus6=""
if [[ $prefix =~ : ]] ; then
    bird_exec=$bird6_exec
    birdc_exec=$birdc6_exec
    bird_sock=$bird6_sock
    bird_cfgs=$bird6_cfgs
    bird_cfgfile=$bird6_cfgfile
    bird_routes=$bird6_routes
    bird_filters=$bird6_filters
    prefixfn=${prefixfn//:/i}
    pfxdot1=${prefix/::\//::1\/}
    minus6="-6"
    # prefix_db=$prefix6_db
fi

subcmd=$1
case $subcmd in
announce)
    if [ "$mux" = all ] ; then
        for cmux in "${!mux2dev[@]}" ; do
            do_announce "$cmux"
        done
    else
        do_announce "$mux"
    fi
    echo "configure \"$bird_cfgfile\"" | $birdc_exec -s "$bird_sock"
    if [ $config_dataplane -eq 1 ] ; then
        ip $minus6 addr add "$pfxdot1" dev lo &> /dev/null || true
        ip $minus6 rule add from "$prefix" table "$kernel_table" \
                pref "$kernel_table" &> /dev/null || true
    fi
    ;;
withdraw)
    if [ "$mux" = all ] ; then
        for cmux in "${!mux2dev[@]}" ; do
            rm -f "$bird_filters/export_${cmux}_$prefixfn.conf"
        done
        ip $minus6 addr del "$pfxdot1" dev lo &> /dev/null || true
        ip $minus6 rule del from "$prefix" table "$kernel_table" \
                pref "$kernel_table" &> /dev/null || true
    else
        rm -f "$bird_filters/export_${mux}_$prefixfn.conf"
    fi
    echo "configure \"$bird_cfgfile\"" | $birdc_exec -s "$bird_sock"
    ;;
*)
    usage
    ;;
esac
