#!/bin/bash
set -eu

progdir=$(cd "$(dirname "$(readlink -f "$0")")"; pwd -P)
source "$progdir/config.sh"

outdir=$1
label=$2

su $USER -c "ssh $REVTR_DB_HOST \"/home/$USER/extract-targets.sh\" $label"

mkdir -p "$outdir"
chown $USER "$outdir"

su $USER -c "scp -r $REVTR_DB_HOST:compute-targets/$label/\* \"$outdir\""

"$progdir/join-targets.py" --workdir "$outdir"
