#!/bin/bash
set -eu

export progdir=$(cd "$(dirname "$(readlink -f "$0")")"; pwd -P)
source "$progdir/config.sh"

tgtdir=$1
outdir=$2

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

mkdir -p "$outdir"

echo "Starting tcpdump"
for mux in "${!mux2octet[@]}" ; do
    devid=${mux2id[$mux]}
    dev=tap$devid
    tcpdump --packet-buffered -n -w "$outdir/$mux.dump" -i "$dev" \
            "dst net $SUPERPREFIX and icmp[icmptype] == icmp-echoreply" \
            &> "$outdir/$mux.log" &
    pid=$!
    echo $pid > "$outdir/$mux.pid"
done

echo "Launching scamper within containers"
for mux in "${!mux2octet[@]}" ; do
    dstlist=$tgtdir/${mux}_targets.txt
    ctxname=$CTX_NAME_PREFIX-$mux
    docker cp --follow-link "$dstlist" "$ctxname:targets.txt"
    docker exec --detach "$ctxname" \
            scamper -f "targets.txt" -o catchment.warts -O warts \
            -p 250 -c "ping -c 2"
done

echo "Waiting for scamper to finish"
running=1
while [[ $running -eq 1 ]] ; do
    running=0
    for mux in "${!mux2octet[@]}" ; do
        ctxname=$CTX_NAME_PREFIX-$mux
        instances=$(docker exec "$ctxname" ps aux | grep scamper \
                | grep -c "catchment" || true)
        if [[ $instances -gt 0 ]] ; then
            fsize=$(docker exec "$ctxname" stat -c %s catchment.warts)
            echo "  $mux running scamper, warts size is $fsize"
            running=1
        fi
    done
    sleep 30s
done

echo "Killing tcpdump instances"
for mux in "${!mux2octet[@]}" ; do
    ctxname=$CTX_NAME_PREFIX-$mux
    docker cp "$ctxname:catchment.warts" "$outdir/$mux.warts"
    pkill --pidfile "$outdir/$mux.pid"
done

sudo chown -R "$USER:$GROUP" "$outdir"