#!/bin/bash
set -eu

progdir=$(cd "$(dirname "$(readlink -f "$0")")"; pwd -P)
source "$progdir/config.sh"

function check_ip_not_on_host {
    local ip=$1
    while read -r pfx ; do
        if check-ip-in-subnet.py "$ip" "$pfx" ; then
            echo "WARNING: IP $ip is connected to the loopback on the host"
        fi
    done < <(ip addr show dev lo | grep -oEe "inet6? [^ ]+" | cut -d " " -f 2)
}

function start_containers {
    echo "Starting revtrvp containers"
    for octet in "${octets[@]}" ; do
        local ip=184.164.$octet.$((128 + 1))
        local ctxname=$CTX_NAME_PREFIX-$octet
        check_ip_not_on_host "$ip"
        echo "  $ctxname on br$octet using $ip"
        docker run --name "$ctxname" --network="br$octet" --ip "$ip" \
                --restart=unless-stopped --detach \
                --log-opt max-size=1g --log-opt max-file=1 \
                revtrvp /root.crt /plvp.config -loglevel debug &> /dev/null
    done
}

function stop_containers {
    echo "Stopping revtrvp containers"
    for octet in "${octets[@]}" ; do
        ctxname=$CTX_NAME_PREFIX-$octet
        if docker ps | grep "$ctxname" &> /dev/null ; then
            echo "  $ctxname"
            docker stop "$ctxname" &> /dev/null
            docker rm "$ctxname" &> /dev/null
        fi
    done
}

die () {
    echo "$1"
    exit 1
}

if [[ $# -lt 1 ]] ; then die "usage: $0 start|stop|restart" ; fi
case $1 in
restart)
    stop_containers
    start_containers
    ;;
start)
    start_containers
    ;;
stop)
    stop_containers
    ;;
*)
    die "usage: $0 start|stop|restart"
    ;;
esac
