#!/bin/bash
set -eu

progdir=$(cd "$(dirname "$(readlink -f "$0")")"; pwd -P)
source "$progdir/config.sh"

function setup_source_routing {
    local octet=$1
    local mux=$2
    teardown_source_routing "$octet"
    echo "Setting up source routing"
    devid=${mux2id[$mux]}
    table=$((BASE_TABLE + octet))
    ip="184.164.$octet.$((128 + 1))"
    gw="100.$((64 + devid)).128.1"
    echo "  $octet $mux: from $ip/32 table $table via $gw"
    ip route add default via $gw table $table
    ip rule add from "$ip/32" table $table pref $table
    ip rule add iif "br$octet" table $table pref $table
}

function teardown_source_routing {
    local octet=$1
    echo "Tearing down source routing for $octet"
    table=$((BASE_TABLE + octet))
    nrules=$(ip rule show pref $table | wc -l)
    echo "  Dropping table $table and $nrules rules"
    ip route flush table $table &> /dev/null || true
    while [[ $(( nrules-- )) -gt 0 ]] ; do
        ip rule del pref $table
    done
}

die () {
    echo "$1"
    exit 1
}

function usage () {
    echo "usage: $0 setup <octet> <mux>"
    echo "   or: $0 teardown <octet>"
    die ""
}

if [[ $# -lt 1 ]] ; then usage ; fi
case $1 in
setup)
    shift
    if [[ $# -lt 2 ]] ; then usage ; fi
    setup_source_routing "$1" "$2"
    ;;
teardown)
    shift
    if [[ $# -lt 1 ]] ; then usage ; fi
    teardown_source_routing "$1"
    ;;
*)
    usage
    ;;
esac