#!/bin/bash
set -eu

progdir=$(cd "$(dirname "$(readlink -f "$0")")"; pwd -P)
source "$progdir/config.sh"

outdir=$1
withroutes=$2
mkdir -p "$outdir"

echo "  Taking snapshot $(basename "$1")"

docker ps > "$outdir/docker-ps.txt"
$CDIR/peering openvpn status > "$outdir/openvpn-status.txt"
ip rule &> "$outdir/host-ip-rule.txt"

for octet in "${octets[@]}" ; do
    table=$((BASE_TABLE + octet))
    prefix="184.164.$octet.0/24"
    # v4addr=184.164.$octet.$((128 + muxid))
    # Add `--ip $v4addr` to Docker to set the IP address

    ip route show table "$table" &> "$outdir/host-ip-route-table-$table.txt"
    # docker run --network "br$octet" -it --rm \
    #         busybox ip addr &> "$outdir/busybox-ip-addr-$mux.txt"
    # docker run --network "br$octet" -it --rm \
    #         busybox ip route &> "$outdir/busybox-ip-route-$mux.txt"
    # docker run --network "br$octet" -it --rm \
    #         busybox ip rule &> "$outdir/busybox-ip-rule-$mux.txt"

    for mux in "${!mux2id[@]}" ; do
        $CDIR/peering bgp adv "$mux" > "$outdir/bgp-adv-$mux.txt"
    done

    if [[ $withroutes -eq 1 ]] ; then
        $CDIR/utils/prefix-propagation/query-route-server.py \
                --log "$outdir/att-routes-$octet.txt" "$prefix" \
                &> "$outdir/att-routes-$octet.log"
    fi
done
