#!/bin/bash
set -eu
set -x

progdir=$(cd "$(dirname "$(readlink -f "$0")")"; pwd -P)
source "$progdir/config.sh"

outdir=$1
withroutes=$2
mkdir -p "$outdir"

docker ps > "$outdir/docker-ps.txt"
./peering openvpn status > "$outdir/openvpn-status.txt"
ip rule &> "$outdir/host-ip-rule.txt"

for mux in "${!mux2octet[@]}" ; do
    muxid=${mux2id[$mux]}
    octet=${mux2octet[$mux]}
    table=$((BASE_TABLE + muxid))
    prefix="184.164.$octet.0/24"
    # v4addr=184.164.$octet.$((128 + muxid))
    # Add `--ip $v4addr` to Docker to set the IP address

    ip route show table "$table" &> "$outdir/host-ip-route-table-$table.txt"
    # docker run --network "br$octet" -it --rm \
    #         busybox ip addr &> "$outdir/busybox-ip-addr-$mux.txt"
    # docker run --network "br$octet" -it --rm \
    #         busybox ip route &> "$outdir/busybox-ip-route-$mux.txt"
    # docker run --network "br$octet" -it --rm \
    #         busybox ip rule &> "$outdir/busybox-ip-rule-$mux.txt"

    ./peering bgp adv "$mux" > "$outdir/bgp-adv-$mux.txt"

    if [[ $withroutes -eq 1 ]] ; then
        ./utils/prefix-propagation/query-route-server.py \
                --log "$outdir/att-routes-$octet.txt" "$prefix" \
                &> "$outdir/att-routes-$octet.log"
    fi
done
